### PR TITLE
Update account.rb

### PR DESCRIPTION
**Pull request by jethroo**
if number is nil, you will set @bank_number to 0 (same for @bank_account_number)

2.0.0p247 :001 > number = nil
 => nil 
2.0.0p247 :002 > nr_str = "#{number}".gsub(/\s/,'')
 => "" 
2.0.0p247 :003 > @bank_number = nr_str.to_i
 => 0 
2.0.0p247 :004 >

### CODE REVIEW

**Comment by ledermann** [comment]
You are right. Please, can you add a test to verify your change?

**Comment by jethroo** [comment]
sure, will do later this day

**Comment by jethroo** [comment]
added tests for my changes and a not tested exception

**Comment by ledermann** [comment]
Thanks!

**Pull request merged**
